# http://docs.travis-ci.com/user/languages/python/

language: python
python:
    - 2.7
    - pypy
    - 3.4
    - 3.5

before_install:
    sudo apt-get install -qq libreoffice-writer

script:
    python setup.py test

sudo: false

